### ISSUE TITLE
aftership component not working - lovelace UI not supported

### ISSUE THREAD

**Issue by vMeph** [tr1plus/ha-aftership#1]
all im getting is:
![1](https://user-images.githubusercontent.com/12812111/42054786-428bfaa6-7b0d-11e8-9967-3a6f35a6e487.jpg)

on my configuration.yaml have set
```
sensor:
  #Package tracking aftership
  - platform: rest
    name: AfterShip Sensor
    resource: https://api.aftership.com/v4/trackings/
    value_template: '{{ value_json["data"]["count"]}}'
    json_attributes:
      - data
    headers:
      aftership-api-key: !secret afteship
      Content-Type: application/json
```
copy state-card-aftership to the directory config\www\custom_ui

in groups:
```
tracks:
  name: Tracking
  entities:
    - sensor.aftership_sensor
```

have set the correct aftership api, if you notice in the pic shows 2 items availabe witch is correct

not sure what im doing wrong, im using HASSIO
